[project]
name = "application"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
    "sentence-transformers>=5.5.1",
    "torch==2.11.0+cu130",
    "torchvision==0.26.0+cu130",
    "torchaudio==2.11.0+cu130",
    "langchain>=1.3.1",
    "langchain-community>=0.4.1",
    "langchain-chroma>=1.1.0",
    "langchain-ollama>=1.1.0",
    "fastapi>=0.136.1",
    #    fastapi web容器
    "uvicorn>=0.47.0",
    #    mysql链接驱动
    "pymysql>=1.2.0",
    #    数据库连接池
    "dbutils>=3.1.2",
    "pyjwt>=2.13.0",
]

[project.scripts]
application = "application.application:main"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.uv]
index-strategy = "unsafe-best-match"

[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"
